//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_41P_SergeevDI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int id_session { get; set; }
        public int id_employee { get; set; }
        public string file_session { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
